version: '3.7'
services:
  proxy:
    image: nginx:stable-alpine3.17
    # If there are multiple deployments of the SSM on the same host then they each need to expose a different PROXY_EXTERNAL_PORT
    ports:
      - ${PROXY_EXTERNAL_PORT:-8089}:80
    expose:
      - 80
    environment:
      # Set the env var "scheme" in the proxy container to $NGINX_SCHEME (if set) or the literal '$scheme' otherwise
      scheme: ${SERVICE_PROTOCOL:-http}
      server_port: ${SERVICE_PORT:-8089}
      kc_proxy_pass: '${EXTERNAL_KEYCLOAK_AUTH_SERVER_URL:-http://keycloak:8080/auth}'
      documentation_url: '${DOCUMENTATION_URL:-https://spyderisk.org/documentation/modeller/latest/}'
    # When nginx starts it does a health check on the "upstream" servers and if none of them in a group are present it will fail.
    # Hence, nginx must start after the ssm and keycloak.
    # See https://docs.nginx.com/nginx/admin-guide/load-balancer/tcp-health-check/
    restart: on-failure
    depends_on:
      - ssm
      - keycloak
      - adaptor
    entrypoint: /tmp/import/entrypoint.sh
    volumes:
      - type: bind
        source: ./provisioning/nginx
        target: /tmp/import
    networks:
      - ssm_adaptor_net

  ssm:
    image: 'spyderisk/system-modeller:${SPYDERISK_VERSION:-dev-20231025T1200}'
    restart: on-failure
    environment:
      # The "SPRING" env variables override the values in application.properties
      # https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config
      SPRING_DATA_MONGODB_HOST: mongo
      # The KEYCLOAK URL must be the external address of the service + "/auth/"
      KEYCLOAK_AUTH_SERVER_URL: ${SERVICE_PROTOCOL:-http}://${SERVICE_DOMAIN:-host.docker.internal}:${SERVICE_PORT:-8089}/auth/
      KEYCLOAK_CREDENTIALS_SECRET: ${KEYCLOAK_CREDENTIALS_SECRET:-DfkQBcVpjbO6gTMXMBUBfHe45UmFhGxk}
      # Knowledgebases source location (must match volume defined below)
      KNOWLEDGEBASES_SOURCE_FOLDER: /knowledgebases
      # Knowledgebases installation location (must match knowledgebases volume defined below)
      KNOWLEDGEBASES_INSTALL_FOLDER: /opt/spyderisk/knowledgebases
    volumes:
      # Persistent named volume for the jena-tdb storage
      - type: volume
        source: jena
        target: /jena-tdb
      - type: bind
        source: ./knowledgebases
        target: /knowledgebases
      # Persistent named volume for storage of knowledgebase data (domain model, images and palettes)
      - type: volume
        source: knowledgebases
        target: /opt/spyderisk/knowledgebases
    depends_on:
      mongo:
        condition: service_started
      keycloak:
        condition: service_healthy
    networks:
      - ssm_adaptor_net

  keycloak:
    image: keycloak/keycloak:21.0
    # WARNING: THIS CONFIGURATION IS INSECURE AND SHOULD ONLY BE USED IN DEVELOPMENT SYSTEMS
    # Override the normal entrypoint of `/opt/keycloak/bin/kc.sh`. See the file provisioning/keycloak/entrypoint.sh for details.
    entrypoint: /tmp/import/entrypoint.sh
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-password}
      KEYCLOAK_CREDENTIALS_SECRET: ${KEYCLOAK_CREDENTIALS_SECRET:-DfkQBcVpjbO6gTMXMBUBfHe45UmFhGxk}
    healthcheck:
      test: ["CMD", "/tmp/import/healthcheck.sh"]
      start_period: 10s
      interval: 30s
      retries: 3
      timeout: 5s
    volumes:
      - type: bind
        source: ./provisioning/keycloak
        target: /tmp/import
    networks:
      - ssm_adaptor_net

  mongo:
    image: mongo:5.0.16-focal
    restart: on-failure
    volumes:
      - type: volume
        source: mongo-db
        target: /data/db
      - type: volume
        source: mongo-configdb
        target: /data/configdb
    networks:
      - ssm_adaptor_net

  adaptor:
    image: 'spyderisk/system-modeller-adaptor:${SPYDERISK_ADAPTOR_VERSION:-dev-20231026T1640}'
    command: 'gunicorn -b 0.0.0.0:8000 -t 0 -w 2 -k uvicorn.workers.UvicornWorker app.main:app'
    env_file:
      - .env_adaptor
    ports:
      - '17643:8000'
    volumes:
      - ./:/code
    networks:
      - ssm_adaptor_net
    depends_on:
      - mongo

networks:
  ssm_adaptor_net:

volumes:
  jena:
  mongo-db:
  mongo-configdb:
  mongodb-data:
  knowledgebases:
