# coding: utf-8

"""
    OpenAPI definition

    SPYDERISK System Modeller (SSM) REST API definitions for domain models, user system models and usage by other applications.

    The version of the OpenAPI document: v3.5.0
    Contact: info@spyderisk.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class AuthzDTO(BaseModel):
    """
    AuthzDTO
    """ # noqa: E501
    read_usernames: Optional[List[StrictStr]] = Field(default=None, alias="readUsernames")
    write_usernames: Optional[List[StrictStr]] = Field(default=None, alias="writeUsernames")
    owner_usernames: Optional[List[StrictStr]] = Field(default=None, alias="ownerUsernames")
    no_role_url: Optional[StrictStr] = Field(default=None, alias="noRoleUrl")
    read_url: Optional[StrictStr] = Field(default=None, alias="readUrl")
    write_url: Optional[StrictStr] = Field(default=None, alias="writeUrl")
    owner_url: Optional[StrictStr] = Field(default=None, alias="ownerUrl")
    __properties: ClassVar[List[str]] = ["readUsernames", "writeUsernames", "ownerUsernames", "noRoleUrl", "readUrl", "writeUrl", "ownerUrl"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AuthzDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AuthzDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "readUsernames": obj.get("readUsernames"),
            "writeUsernames": obj.get("writeUsernames"),
            "ownerUsernames": obj.get("ownerUsernames"),
            "noRoleUrl": obj.get("noRoleUrl"),
            "readUrl": obj.get("readUrl"),
            "writeUrl": obj.get("writeUrl"),
            "ownerUrl": obj.get("ownerUrl")
        })
        return _obj


