# coding: utf-8

"""
    OpenAPI definition

    SPYDERISK System Modeller (SSM) REST API definitions for domain models, user system models and usage by other applications.

    The version of the OpenAPI document: v3.5.0
    Contact: info@spyderisk.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ThreatDB(BaseModel):
    """
    ThreatDB
    """ # noqa: E501
    uri: Optional[StrictStr] = None
    type: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    label: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    parent: Optional[StrictStr] = None
    threatens: Optional[StrictStr] = None
    applies_to: Optional[StrictStr] = Field(default=None, alias="appliesTo")
    frequency: Optional[StrictStr] = None
    entry_points: Optional[List[StrictStr]] = Field(default=None, alias="entryPoints")
    secondary_effect_conditions: Optional[List[StrictStr]] = Field(default=None, alias="secondaryEffectConditions")
    misbehaviours: Optional[List[StrictStr]] = None
    blocked_by_csg: Optional[List[StrictStr]] = Field(default=None, alias="blockedByCSG")
    mitigated_by_csg: Optional[List[StrictStr]] = Field(default=None, alias="mitigatedByCSG")
    triggered_by_csg: Optional[List[StrictStr]] = Field(default=None, alias="triggeredByCSG")
    triggered: Optional[StrictBool] = None
    min_of: Optional[StrictStr] = Field(default=None, alias="minOf")
    max_of: Optional[StrictStr] = Field(default=None, alias="maxOf")
    has_min: Optional[StrictStr] = Field(default=None, alias="hasMin")
    has_max: Optional[StrictStr] = Field(default=None, alias="hasMax")
    current_risk: Optional[StrictBool] = Field(default=None, alias="currentRisk")
    future_risk: Optional[StrictBool] = Field(default=None, alias="futureRisk")
    secondary_threat: Optional[StrictBool] = Field(default=None, alias="secondaryThreat")
    normal_operation: Optional[StrictBool] = Field(default=None, alias="normalOperation")
    risk: Optional[StrictStr] = None
    direct_misbehaviours: Optional[List[StrictStr]] = Field(default=None, alias="directMisbehaviours")
    indirect_misbehaviours: Optional[List[StrictStr]] = Field(default=None, alias="indirectMisbehaviours")
    indirect_threats: Optional[List[StrictStr]] = Field(default=None, alias="indirectThreats")
    caused_by: Optional[List[StrictStr]] = Field(default=None, alias="causedBy")
    initial_cause: Optional[StrictBool] = Field(default=None, alias="initialCause")
    root_cause: Optional[StrictBool] = Field(default=None, alias="rootCause")
    likelihood: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["uri", "type", "id", "label", "description", "parent", "threatens", "appliesTo", "frequency", "entryPoints", "secondaryEffectConditions", "misbehaviours", "blockedByCSG", "mitigatedByCSG", "triggeredByCSG", "triggered", "minOf", "maxOf", "hasMin", "hasMax", "currentRisk", "futureRisk", "secondaryThreat", "normalOperation", "risk", "directMisbehaviours", "indirectMisbehaviours", "indirectThreats", "causedBy", "initialCause", "rootCause", "likelihood"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ThreatDB from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ThreatDB from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uri": obj.get("uri"),
            "type": obj.get("type"),
            "id": obj.get("id"),
            "label": obj.get("label"),
            "description": obj.get("description"),
            "parent": obj.get("parent"),
            "threatens": obj.get("threatens"),
            "appliesTo": obj.get("appliesTo"),
            "frequency": obj.get("frequency"),
            "entryPoints": obj.get("entryPoints"),
            "secondaryEffectConditions": obj.get("secondaryEffectConditions"),
            "misbehaviours": obj.get("misbehaviours"),
            "blockedByCSG": obj.get("blockedByCSG"),
            "mitigatedByCSG": obj.get("mitigatedByCSG"),
            "triggeredByCSG": obj.get("triggeredByCSG"),
            "triggered": obj.get("triggered"),
            "minOf": obj.get("minOf"),
            "maxOf": obj.get("maxOf"),
            "hasMin": obj.get("hasMin"),
            "hasMax": obj.get("hasMax"),
            "currentRisk": obj.get("currentRisk"),
            "futureRisk": obj.get("futureRisk"),
            "secondaryThreat": obj.get("secondaryThreat"),
            "normalOperation": obj.get("normalOperation"),
            "risk": obj.get("risk"),
            "directMisbehaviours": obj.get("directMisbehaviours"),
            "indirectMisbehaviours": obj.get("indirectMisbehaviours"),
            "indirectThreats": obj.get("indirectThreats"),
            "causedBy": obj.get("causedBy"),
            "initialCause": obj.get("initialCause"),
            "rootCause": obj.get("rootCause"),
            "likelihood": obj.get("likelihood")
        })
        return _obj


