# coding: utf-8

"""
    OpenAPI definition

    SPYDERISK System Modeller (SSM) REST API definitions for domain models, user system models and usage by other applications.

    The version of the OpenAPI document: v3.5.0
    Contact: info@spyderisk.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from ssmclientlib.models.level import Level
from ssmclientlib.models.semantic_entity import SemanticEntity
from typing import Optional, Set
from typing_extensions import Self

class TrustworthinessAttributeSet(BaseModel):
    """
    TrustworthinessAttributeSet
    """ # noqa: E501
    uri: Optional[StrictStr] = None
    label: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    parents: Optional[List[StrictStr]] = None
    asset: Optional[StrictStr] = None
    attribute: Optional[SemanticEntity] = None
    causing_misbehaviour_set: Optional[StrictStr] = Field(default=None, alias="causingMisbehaviourSet")
    asserted_tw_level: Optional[Level] = Field(default=None, alias="assertedTWLevel")
    inferred_tw_level: Optional[Level] = Field(default=None, alias="inferredTWLevel")
    tw_level_asserted: Optional[StrictBool] = Field(default=None, alias="twLevelAsserted")
    visible: Optional[StrictBool] = None
    id: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["uri", "label", "description", "parents", "asset", "attribute", "causingMisbehaviourSet", "assertedTWLevel", "inferredTWLevel", "twLevelAsserted", "visible", "id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TrustworthinessAttributeSet from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of attribute
        if self.attribute:
            _dict['attribute'] = self.attribute.to_dict()
        # override the default output from pydantic by calling `to_dict()` of asserted_tw_level
        if self.asserted_tw_level:
            _dict['assertedTWLevel'] = self.asserted_tw_level.to_dict()
        # override the default output from pydantic by calling `to_dict()` of inferred_tw_level
        if self.inferred_tw_level:
            _dict['inferredTWLevel'] = self.inferred_tw_level.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TrustworthinessAttributeSet from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uri": obj.get("uri"),
            "label": obj.get("label"),
            "description": obj.get("description"),
            "parents": obj.get("parents"),
            "asset": obj.get("asset"),
            "attribute": SemanticEntity.from_dict(obj["attribute"]) if obj.get("attribute") is not None else None,
            "causingMisbehaviourSet": obj.get("causingMisbehaviourSet"),
            "assertedTWLevel": Level.from_dict(obj["assertedTWLevel"]) if obj.get("assertedTWLevel") is not None else None,
            "inferredTWLevel": Level.from_dict(obj["inferredTWLevel"]) if obj.get("inferredTWLevel") is not None else None,
            "twLevelAsserted": obj.get("twLevelAsserted"),
            "visible": obj.get("visible"),
            "id": obj.get("id")
        })
        return _obj


