# generated by datamodel-codegen:
#   filename:  aira_schema.json
#   timestamp: 2025-02-10T16:35:47+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict

from datetime import datetime

class Config(BaseModel):
    python_version_description: str
    python_version: str
    framework_type_description: str
    framework_type: str
    framework_version_description: str
    access_description: str
    access: str
    queries_limited_description: str
    queries_limited: bool
    model_type_description: str
    model_type: str
    algorithm_description: str
    algorithm: str
    output_format_description: str
    output_format: str

    model_config = ConfigDict(protected_namespaces=())


class Model(BaseModel):
    model_description: str
    file_description: str
    file: Dict[str, Any]
    config: Config

    model_config = ConfigDict(protected_namespaces=())

class Data(BaseModel):
    sensitive_attributes_description: str
    sensitive_attributes: List[str]
    input_shape_description: str
    input_shape: str
    num_of_classes_description: str
    num_of_classes: int
    x_train_description: str
    x_train: bool
    y_train_description: str
    y_train: bool
    y_pred_train_description: str
    y_pred_train: bool
    x_test_description: str
    x_test: bool
    y_test_description: str
    y_test: bool
    y_pred_test_description: str
    y_pred_test: bool
    output_shape_description: str


class Attack(BaseModel):
    name_description: str
    name: str
    attacked_model_description: str
    attacked_model: str
    framework_description: str
    framework: str


class IdealRange(BaseModel):
    minimum_description: str
    minimum: float
    maximum_description: str
    maximum: float


class Accuracy(BaseModel):
    worst_run_description: str
    worst_run: float
    average_run_description: str
    average_run: float
    std_dev_run_description: str
    std_dev_run: float
    ideal_range_description: str
    ideal_range: IdealRange


class Value1(BaseModel):
    id_description: str
    text: str


class Precision(BaseModel):
    worst_run_description: str
    worst_run: float
    average_run_description: str
    average_run: float
    std_dev_run_description: str
    std_dev_run: float
    ideal_range_description: str
    ideal_range: IdealRange


class Recall(BaseModel):
    worst_run_description: str
    worst_run: float
    average_run_description: str
    average_run: float
    std_dev_run_description: str
    std_dev_run: float
    ideal_range_description: str
    ideal_range: IdealRange


class F1(BaseModel):
    worst_run_description: str
    worst_run: float
    average_run_description: str
    average_run: float
    std_dev_run_description: str
    std_dev_run: float
    ideal_range_description: str
    ideal_range: IdealRange


class AucRoc(BaseModel):
    worst_run_description: str
    worst_run: float
    average_run_description: str
    average_run: float
    std_dev_run_description: str
    std_dev_run: float
    ideal_range_description: str
    ideal_range: IdealRange


class Roc(BaseModel):
    auc_roc_description: str
    auc_roc: AucRoc
    false_positive_rates_description: str
    false_positive_rates: List[float]
    true_positive_rates_description: str
    true_positive_rates: List[float]


class Value(BaseModel):
    value_description: str
    value: Value1
    precision_description: str
    precision: Precision
    recall_description: str
    recall: Recall
    f1_description: str
    f1: F1
    frequency_description: str
    frequency: float
    roc_description: str
    roc: Optional[Roc] = None


class AttributeScore(BaseModel):
    feature_name_description: str
    feature_name: str
    accuracy_description: str
    accuracy: Accuracy
    values_description: str
    values: List[Value]
    highest_frequency_description: str
    highest_frequency: float
    precision_risk_score_description: str
    precision_risk_score: float
    recall_risk_score_description: str
    recall_risk_score: float
    f1_risk_score_description: str
    f1_risk_score: float


class RiskScores(BaseModel):
    accuracy_risk_score_description: str
    accuracy_risk_score: float
    precision_risk_score_description: str
    precision_risk_score: float
    recall_risk_score_description: str
    recall_risk_score: float
    f1_risk_score_description: str
    f1_risk_score: float
    attribute_scores_description: str
    attribute_scores: List[AttributeScore]


class AttackFamily(BaseModel):
    name_description: str
    name: str
    attacks_description: str
    attacks: List[Attack]
    risk_scores_description: str
    risk_scores: RiskScores


class OverallPrivacyHealth(BaseModel):
    accuracy_health_score_description: str
    accuracy_health_score: float
    precision_health_score_description: str
    precision_health_score: float
    recall_health_score_description: str
    recall_health_score: float
    f1_health_score_description: str
    f1_health_score: float


class ProducerId(BaseModel):
    producer_description: str
    producer: str
    name_description: str
    name: str
    version_description: str
    version: str


class Privacy(BaseModel):
    aggregate_description: str
    aggregate: float
    attack_families_description: str
    attack_families: List[AttackFamily]
    overall_privacy_health_description: str
    overall_privacy_health: OverallPrivacyHealth
    producer_id_description: str
    producer_id: ProducerId


class Assessment(BaseModel):
    privacy_description: str
    privacy: Privacy
    aggregate_score_description: str
    aggregate_score: float


class Result(BaseModel):
    assessment: Assessment


class Threshold(BaseModel):
    name: str
    value: List[float]


class Context(BaseModel):
    metrics_description: str
    metrics: List[str]
    thresholds_description: str
    thresholds: List[Threshold]
    advanced_description: str
    advanced: List
    params_description: str
    params: List


class Dimension(BaseModel):
    name_description: str
    name: str
    context_description: str
    context: Context


class AiraReport(BaseModel):
    id_description: str
    id: str
    project_id_description: str
    project_id: str
    number_of_runs_description: str
    number_of_runs: int
    run_shadow: bool
    attack_families: List[str]
    risk_frameworks: List[str]
    assessment_id_description: str
    assessment_id: str
    created_date_description: str
    created_date: datetime
    started_date_description: str
    started_date: str
    completed_date_description: str
    completed_date: datetime
    created_by_description: str
    created_by: str
    status_description: str
    status: str
    mode_description: str
    mode: str
    model: Model
    data: Data
    result: Result
    dimensions: List[Dimension]
