# generated by datamodel-codegen:
#   filename:  device_information.json
#   timestamp: 2025-09-23T14:24:18+00:00

#from __future__ import annotations

from typing import List, Dict, Optional

from pydantic import RootModel, BaseModel, Field


class CveItem(BaseModel):
    cve: str
    desc: str


class DetectedCveItem(BaseModel):
    name: str
    product: str
    version: str
    cve: Optional[List[CveItem]] = None

    def __str__(self):
        return f"(name: {self.name}, product: {self.product}, version: {self.version})"

class NAToolEntity(BaseModel):
    ip: str
    mac: Optional[str] = None
    mac_lookup: Optional[str] = "N/A"
    os: Optional[str] = "N/A"
    open_tcp_ports: Optional[List[int]] = None
    open_udp_ports: Optional[List[int]] = None
    detected_cve: Optional[List[DetectedCveItem]] = None
    score: float

class NAToolReport(RootModel[Dict[int, NAToolEntity]]):
    pass

