# generated by datamodel-codegen:
#   filename:  aira_schema.json
#   timestamp: 2025-02-10T16:35:47+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict

from datetime import datetime

#TODO needs to be a proper model 
class NAToolReport(BaseModel):
    id_description: str
    id: str

