# coding: utf-8

"""
    OpenAPI definition

    SPYDERISK System Modeller (SSM) REST API definitions for domain models, user system models and usage by other applications.  # noqa: E501

    The version of the OpenAPI document: v3.4.0
    Contact: info@spyderisk.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from ssm_api_client.configuration import Configuration


class TrustworthinessAttributeDB(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'uri': 'str',
        'type': 'str',
        'id': 'str',
        'label': 'str',
        'description': 'str',
        'meta_located_at': 'list[str]',
        'min_of': 'str',
        'max_of': 'str',
        'has_min': 'str',
        'has_max': 'str',
        'visible': 'bool'
    }

    attribute_map = {
        'uri': 'uri',
        'type': 'type',
        'id': 'id',
        'label': 'label',
        'description': 'description',
        'meta_located_at': 'metaLocatedAt',
        'min_of': 'minOf',
        'max_of': 'maxOf',
        'has_min': 'hasMin',
        'has_max': 'hasMax',
        'visible': 'visible'
    }

    def __init__(self, uri=None, type=None, id=None, label=None, description=None, meta_located_at=None, min_of=None, max_of=None, has_min=None, has_max=None, visible=None, local_vars_configuration=None):  # noqa: E501
        """TrustworthinessAttributeDB - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._uri = None
        self._type = None
        self._id = None
        self._label = None
        self._description = None
        self._meta_located_at = None
        self._min_of = None
        self._max_of = None
        self._has_min = None
        self._has_max = None
        self._visible = None
        self.discriminator = None

        if uri is not None:
            self.uri = uri
        if type is not None:
            self.type = type
        if id is not None:
            self.id = id
        if label is not None:
            self.label = label
        if description is not None:
            self.description = description
        if meta_located_at is not None:
            self.meta_located_at = meta_located_at
        if min_of is not None:
            self.min_of = min_of
        if max_of is not None:
            self.max_of = max_of
        if has_min is not None:
            self.has_min = has_min
        if has_max is not None:
            self.has_max = has_max
        if visible is not None:
            self.visible = visible

    @property
    def uri(self):
        """Gets the uri of this TrustworthinessAttributeDB.  # noqa: E501


        :return: The uri of this TrustworthinessAttributeDB.  # noqa: E501
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this TrustworthinessAttributeDB.


        :param uri: The uri of this TrustworthinessAttributeDB.  # noqa: E501
        :type: str
        """

        self._uri = uri

    @property
    def type(self):
        """Gets the type of this TrustworthinessAttributeDB.  # noqa: E501


        :return: The type of this TrustworthinessAttributeDB.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this TrustworthinessAttributeDB.


        :param type: The type of this TrustworthinessAttributeDB.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def id(self):
        """Gets the id of this TrustworthinessAttributeDB.  # noqa: E501


        :return: The id of this TrustworthinessAttributeDB.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TrustworthinessAttributeDB.


        :param id: The id of this TrustworthinessAttributeDB.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def label(self):
        """Gets the label of this TrustworthinessAttributeDB.  # noqa: E501


        :return: The label of this TrustworthinessAttributeDB.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this TrustworthinessAttributeDB.


        :param label: The label of this TrustworthinessAttributeDB.  # noqa: E501
        :type: str
        """

        self._label = label

    @property
    def description(self):
        """Gets the description of this TrustworthinessAttributeDB.  # noqa: E501


        :return: The description of this TrustworthinessAttributeDB.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this TrustworthinessAttributeDB.


        :param description: The description of this TrustworthinessAttributeDB.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def meta_located_at(self):
        """Gets the meta_located_at of this TrustworthinessAttributeDB.  # noqa: E501


        :return: The meta_located_at of this TrustworthinessAttributeDB.  # noqa: E501
        :rtype: list[str]
        """
        return self._meta_located_at

    @meta_located_at.setter
    def meta_located_at(self, meta_located_at):
        """Sets the meta_located_at of this TrustworthinessAttributeDB.


        :param meta_located_at: The meta_located_at of this TrustworthinessAttributeDB.  # noqa: E501
        :type: list[str]
        """

        self._meta_located_at = meta_located_at

    @property
    def min_of(self):
        """Gets the min_of of this TrustworthinessAttributeDB.  # noqa: E501


        :return: The min_of of this TrustworthinessAttributeDB.  # noqa: E501
        :rtype: str
        """
        return self._min_of

    @min_of.setter
    def min_of(self, min_of):
        """Sets the min_of of this TrustworthinessAttributeDB.


        :param min_of: The min_of of this TrustworthinessAttributeDB.  # noqa: E501
        :type: str
        """

        self._min_of = min_of

    @property
    def max_of(self):
        """Gets the max_of of this TrustworthinessAttributeDB.  # noqa: E501


        :return: The max_of of this TrustworthinessAttributeDB.  # noqa: E501
        :rtype: str
        """
        return self._max_of

    @max_of.setter
    def max_of(self, max_of):
        """Sets the max_of of this TrustworthinessAttributeDB.


        :param max_of: The max_of of this TrustworthinessAttributeDB.  # noqa: E501
        :type: str
        """

        self._max_of = max_of

    @property
    def has_min(self):
        """Gets the has_min of this TrustworthinessAttributeDB.  # noqa: E501


        :return: The has_min of this TrustworthinessAttributeDB.  # noqa: E501
        :rtype: str
        """
        return self._has_min

    @has_min.setter
    def has_min(self, has_min):
        """Sets the has_min of this TrustworthinessAttributeDB.


        :param has_min: The has_min of this TrustworthinessAttributeDB.  # noqa: E501
        :type: str
        """

        self._has_min = has_min

    @property
    def has_max(self):
        """Gets the has_max of this TrustworthinessAttributeDB.  # noqa: E501


        :return: The has_max of this TrustworthinessAttributeDB.  # noqa: E501
        :rtype: str
        """
        return self._has_max

    @has_max.setter
    def has_max(self, has_max):
        """Sets the has_max of this TrustworthinessAttributeDB.


        :param has_max: The has_max of this TrustworthinessAttributeDB.  # noqa: E501
        :type: str
        """

        self._has_max = has_max

    @property
    def visible(self):
        """Gets the visible of this TrustworthinessAttributeDB.  # noqa: E501


        :return: The visible of this TrustworthinessAttributeDB.  # noqa: E501
        :rtype: bool
        """
        return self._visible

    @visible.setter
    def visible(self, visible):
        """Sets the visible of this TrustworthinessAttributeDB.


        :param visible: The visible of this TrustworthinessAttributeDB.  # noqa: E501
        :type: bool
        """

        self._visible = visible

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TrustworthinessAttributeDB):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TrustworthinessAttributeDB):
            return True

        return self.to_dict() != other.to_dict()
