# coding: utf-8

"""
    OpenAPI definition

    SPYDERISK System Modeller (SSM) REST API definitions for domain models, user system models and usage by other applications.  # noqa: E501

    The version of the OpenAPI document: v3.4.0
    Contact: info@spyderisk.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from ssm_api_client.configuration import Configuration


class TrustworthinessAttributeSet(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'uri': 'str',
        'label': 'str',
        'description': 'str',
        'parents': 'list[str]',
        'asset': 'str',
        'attribute': 'SemanticEntity',
        'causing_misbehaviour_set': 'str',
        'asserted_tw_level': 'Level',
        'inferred_tw_level': 'Level',
        'tw_level_asserted': 'bool',
        'visible': 'bool',
        'id': 'str'
    }

    attribute_map = {
        'uri': 'uri',
        'label': 'label',
        'description': 'description',
        'parents': 'parents',
        'asset': 'asset',
        'attribute': 'attribute',
        'causing_misbehaviour_set': 'causingMisbehaviourSet',
        'asserted_tw_level': 'assertedTWLevel',
        'inferred_tw_level': 'inferredTWLevel',
        'tw_level_asserted': 'twLevelAsserted',
        'visible': 'visible',
        'id': 'id'
    }

    def __init__(self, uri=None, label=None, description=None, parents=None, asset=None, attribute=None, causing_misbehaviour_set=None, asserted_tw_level=None, inferred_tw_level=None, tw_level_asserted=None, visible=None, id=None, local_vars_configuration=None):  # noqa: E501
        """TrustworthinessAttributeSet - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._uri = None
        self._label = None
        self._description = None
        self._parents = None
        self._asset = None
        self._attribute = None
        self._causing_misbehaviour_set = None
        self._asserted_tw_level = None
        self._inferred_tw_level = None
        self._tw_level_asserted = None
        self._visible = None
        self._id = None
        self.discriminator = None

        if uri is not None:
            self.uri = uri
        if label is not None:
            self.label = label
        if description is not None:
            self.description = description
        if parents is not None:
            self.parents = parents
        if asset is not None:
            self.asset = asset
        if attribute is not None:
            self.attribute = attribute
        if causing_misbehaviour_set is not None:
            self.causing_misbehaviour_set = causing_misbehaviour_set
        if asserted_tw_level is not None:
            self.asserted_tw_level = asserted_tw_level
        if inferred_tw_level is not None:
            self.inferred_tw_level = inferred_tw_level
        if tw_level_asserted is not None:
            self.tw_level_asserted = tw_level_asserted
        if visible is not None:
            self.visible = visible
        if id is not None:
            self.id = id

    @property
    def uri(self):
        """Gets the uri of this TrustworthinessAttributeSet.  # noqa: E501


        :return: The uri of this TrustworthinessAttributeSet.  # noqa: E501
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this TrustworthinessAttributeSet.


        :param uri: The uri of this TrustworthinessAttributeSet.  # noqa: E501
        :type: str
        """

        self._uri = uri

    @property
    def label(self):
        """Gets the label of this TrustworthinessAttributeSet.  # noqa: E501


        :return: The label of this TrustworthinessAttributeSet.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this TrustworthinessAttributeSet.


        :param label: The label of this TrustworthinessAttributeSet.  # noqa: E501
        :type: str
        """

        self._label = label

    @property
    def description(self):
        """Gets the description of this TrustworthinessAttributeSet.  # noqa: E501


        :return: The description of this TrustworthinessAttributeSet.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this TrustworthinessAttributeSet.


        :param description: The description of this TrustworthinessAttributeSet.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def parents(self):
        """Gets the parents of this TrustworthinessAttributeSet.  # noqa: E501


        :return: The parents of this TrustworthinessAttributeSet.  # noqa: E501
        :rtype: list[str]
        """
        return self._parents

    @parents.setter
    def parents(self, parents):
        """Sets the parents of this TrustworthinessAttributeSet.


        :param parents: The parents of this TrustworthinessAttributeSet.  # noqa: E501
        :type: list[str]
        """

        self._parents = parents

    @property
    def asset(self):
        """Gets the asset of this TrustworthinessAttributeSet.  # noqa: E501


        :return: The asset of this TrustworthinessAttributeSet.  # noqa: E501
        :rtype: str
        """
        return self._asset

    @asset.setter
    def asset(self, asset):
        """Sets the asset of this TrustworthinessAttributeSet.


        :param asset: The asset of this TrustworthinessAttributeSet.  # noqa: E501
        :type: str
        """

        self._asset = asset

    @property
    def attribute(self):
        """Gets the attribute of this TrustworthinessAttributeSet.  # noqa: E501


        :return: The attribute of this TrustworthinessAttributeSet.  # noqa: E501
        :rtype: SemanticEntity
        """
        return self._attribute

    @attribute.setter
    def attribute(self, attribute):
        """Sets the attribute of this TrustworthinessAttributeSet.


        :param attribute: The attribute of this TrustworthinessAttributeSet.  # noqa: E501
        :type: SemanticEntity
        """

        self._attribute = attribute

    @property
    def causing_misbehaviour_set(self):
        """Gets the causing_misbehaviour_set of this TrustworthinessAttributeSet.  # noqa: E501


        :return: The causing_misbehaviour_set of this TrustworthinessAttributeSet.  # noqa: E501
        :rtype: str
        """
        return self._causing_misbehaviour_set

    @causing_misbehaviour_set.setter
    def causing_misbehaviour_set(self, causing_misbehaviour_set):
        """Sets the causing_misbehaviour_set of this TrustworthinessAttributeSet.


        :param causing_misbehaviour_set: The causing_misbehaviour_set of this TrustworthinessAttributeSet.  # noqa: E501
        :type: str
        """

        self._causing_misbehaviour_set = causing_misbehaviour_set

    @property
    def asserted_tw_level(self):
        """Gets the asserted_tw_level of this TrustworthinessAttributeSet.  # noqa: E501


        :return: The asserted_tw_level of this TrustworthinessAttributeSet.  # noqa: E501
        :rtype: Level
        """
        return self._asserted_tw_level

    @asserted_tw_level.setter
    def asserted_tw_level(self, asserted_tw_level):
        """Sets the asserted_tw_level of this TrustworthinessAttributeSet.


        :param asserted_tw_level: The asserted_tw_level of this TrustworthinessAttributeSet.  # noqa: E501
        :type: Level
        """

        self._asserted_tw_level = asserted_tw_level

    @property
    def inferred_tw_level(self):
        """Gets the inferred_tw_level of this TrustworthinessAttributeSet.  # noqa: E501


        :return: The inferred_tw_level of this TrustworthinessAttributeSet.  # noqa: E501
        :rtype: Level
        """
        return self._inferred_tw_level

    @inferred_tw_level.setter
    def inferred_tw_level(self, inferred_tw_level):
        """Sets the inferred_tw_level of this TrustworthinessAttributeSet.


        :param inferred_tw_level: The inferred_tw_level of this TrustworthinessAttributeSet.  # noqa: E501
        :type: Level
        """

        self._inferred_tw_level = inferred_tw_level

    @property
    def tw_level_asserted(self):
        """Gets the tw_level_asserted of this TrustworthinessAttributeSet.  # noqa: E501


        :return: The tw_level_asserted of this TrustworthinessAttributeSet.  # noqa: E501
        :rtype: bool
        """
        return self._tw_level_asserted

    @tw_level_asserted.setter
    def tw_level_asserted(self, tw_level_asserted):
        """Sets the tw_level_asserted of this TrustworthinessAttributeSet.


        :param tw_level_asserted: The tw_level_asserted of this TrustworthinessAttributeSet.  # noqa: E501
        :type: bool
        """

        self._tw_level_asserted = tw_level_asserted

    @property
    def visible(self):
        """Gets the visible of this TrustworthinessAttributeSet.  # noqa: E501


        :return: The visible of this TrustworthinessAttributeSet.  # noqa: E501
        :rtype: bool
        """
        return self._visible

    @visible.setter
    def visible(self, visible):
        """Sets the visible of this TrustworthinessAttributeSet.


        :param visible: The visible of this TrustworthinessAttributeSet.  # noqa: E501
        :type: bool
        """

        self._visible = visible

    @property
    def id(self):
        """Gets the id of this TrustworthinessAttributeSet.  # noqa: E501


        :return: The id of this TrustworthinessAttributeSet.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TrustworthinessAttributeSet.


        :param id: The id of this TrustworthinessAttributeSet.  # noqa: E501
        :type: str
        """

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TrustworthinessAttributeSet):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TrustworthinessAttributeSet):
            return True

        return self.to_dict() != other.to_dict()
