# coding: utf-8

"""
    OpenAPI definition

    SPYDERISK System Modeller (SSM) REST API definitions for domain models, user system models and usage by other applications.  # noqa: E501

    The version of the OpenAPI document: v3.4.0
    Contact: info@spyderisk.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from ssm_api_client.configuration import Configuration


class UpdateModelResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'name': 'str',
        'description': 'str',
        'domain_graph': 'str',
        'created': 'str',
        'modified': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'description': 'description',
        'domain_graph': 'domainGraph',
        'created': 'created',
        'modified': 'modified'
    }

    def __init__(self, id=None, name=None, description=None, domain_graph=None, created=None, modified=None, local_vars_configuration=None):  # noqa: E501
        """UpdateModelResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._name = None
        self._description = None
        self._domain_graph = None
        self._created = None
        self._modified = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if domain_graph is not None:
            self.domain_graph = domain_graph
        if created is not None:
            self.created = created
        if modified is not None:
            self.modified = modified

    @property
    def id(self):
        """Gets the id of this UpdateModelResponse.  # noqa: E501


        :return: The id of this UpdateModelResponse.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UpdateModelResponse.


        :param id: The id of this UpdateModelResponse.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this UpdateModelResponse.  # noqa: E501


        :return: The name of this UpdateModelResponse.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this UpdateModelResponse.


        :param name: The name of this UpdateModelResponse.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this UpdateModelResponse.  # noqa: E501


        :return: The description of this UpdateModelResponse.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this UpdateModelResponse.


        :param description: The description of this UpdateModelResponse.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def domain_graph(self):
        """Gets the domain_graph of this UpdateModelResponse.  # noqa: E501


        :return: The domain_graph of this UpdateModelResponse.  # noqa: E501
        :rtype: str
        """
        return self._domain_graph

    @domain_graph.setter
    def domain_graph(self, domain_graph):
        """Sets the domain_graph of this UpdateModelResponse.


        :param domain_graph: The domain_graph of this UpdateModelResponse.  # noqa: E501
        :type: str
        """

        self._domain_graph = domain_graph

    @property
    def created(self):
        """Gets the created of this UpdateModelResponse.  # noqa: E501


        :return: The created of this UpdateModelResponse.  # noqa: E501
        :rtype: str
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this UpdateModelResponse.


        :param created: The created of this UpdateModelResponse.  # noqa: E501
        :type: str
        """

        self._created = created

    @property
    def modified(self):
        """Gets the modified of this UpdateModelResponse.  # noqa: E501


        :return: The modified of this UpdateModelResponse.  # noqa: E501
        :rtype: str
        """
        return self._modified

    @modified.setter
    def modified(self, modified):
        """Sets the modified of this UpdateModelResponse.


        :param modified: The modified of this UpdateModelResponse.  # noqa: E501
        :type: str
        """

        self._modified = modified

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateModelResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UpdateModelResponse):
            return True

        return self.to_dict() != other.to_dict()
