name: Docker Image CI

on:
  push:
    branches: [ "dev", "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build the Docker image
      # The metadata inside the image will include the final git commit SHA and the time of the final commit.
      # The tag applied to the image will be like spyderisk/system-modeller-adaptor:<branch-name>-<timestamp>
      # e.g. spyderisk/system-modeller-adaptor:dev-20230405T1012
      # Where the timestamp is the time of the final commit in the build.
      # In addition, the image is tagged with spyderisk/system-modeller-adaptor:<branch-name>-latest
      run: |
        TAG_ROOT=spyderisk/system-modeller-adaptor
        TIMESTAMP=$(git show -s --format=%cI ${GITHUB_SHA})
        SHORT_TIME=$(echo ${TIMESTAMP} | sed 's/[-:]//g')
        REF_END=$(echo ${GITHUB_REF} | sed 's/.*\///')
        TAG_DATE=${TAG_ROOT}:${REF_END}-${SHORT_TIME:0:13}
        TAG_LATEST=${TAG_ROOT}:${REF_END}-latest
        echo "TAG_DATE=${TAG_DATE}" >> ${GITHUB_ENV}
        echo "TAG_LATEST=${TAG_LATEST}" >> ${GITHUB_ENV}
        docker build --tag ${TAG_DATE} --tag ${TAG_LATEST} --build-arg CI_COMMIT_SHA=${GITHUB_SHA} --build-arg CI_COMMIT_TIMESTAMP=${TIMESTAMP} --file Dockerfile "."

    - name: Push Docker image to registry
      run: | 
        docker login -u ${{ vars.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_RW_SECRET }}
        docker push ${TAG_DATE}
        docker push ${TAG_LATEST}
